import = ["/home/ar4sh/dots/alacritty/colors.toml", "/home/ar4sh/dots/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
#history = 10000
#multiplier = 3
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 23

[window.padding]
x = 3
y = 3
