#!/bin/bash

if pgrep -x "waybar" > /dev/null
then
    pkill waybar
else
    waybar > /dev/null &
fi


if pgrep -x "nm-applet" > /dev/null
then
    pkill nm-applet
else
    nm-applet --indicator > /dev/null &
fi
