#!/bin/bash

if pgrep -x "waybar" > /dev/null
then
    pkill waybar
    if pgrep -x "nm-applet"; then
        pkill nm-applet
    fi
else
    waybar > /dev/null &
    nm-applet --indicator > /dev/null &
fi

