#!/bin/bash

update_border() {
    local window_count
    window_count=$(hyprctl activeworkspace -j | jq '.windows')

    if [[ "$window_count" -le 1 ]]; then
        hyprctl keyword general:border_size 0 >/dev/null
    else
        hyprctl keyword general:border_size 1 >/dev/null
    fi
}

socket="${XDG_RUNTIME_DIR}/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock"

update_border

socat -u "UNIX-CONNECT:${socket}" - | while IFS= read -r line; do
    case "${line%%>>*}" in
        openwindow|closewindow|movewindow|workspace|focusedmon)
            update_border
            ;;
    esac
done
