#!/bin/bash

with_slurp() {
  out=~/Pictures/Screenshots/slurp/$(date '+%Y_%m_%d_%H%M%S').png
  grim -g "$(slurp -d)" - | swappy -f - -o - | tee "$out" | wl-copy
  printf '%s' "$out"
}

without_slurp() {
  out=~/Pictures/Screenshots/fullscreen/$(date '+%Y_%m_%d_%H%M%S').png
  grim - | swappy -f - -o - | tee "$out" | wl-copy
  printf '%s' "$out"
}

if [[ "$1" == "slurp" ]]; then
  file=$(with_slurp)
  notify-send -a 'Grim' -u low -i "$file" 'Screenshot' "Screenshot saved with Swappy"
elif [[ "$1" == "no_slurp" ]]; then
  file=$(without_slurp)
  notify-send -a 'Grim' -u low -i "$file" 'Screenshot' "FullScreen screenshot saved with Swappy"
fi

