#!/bin/bash

with_slurp() {
  grim -g "$(slurp -d)" - | swappy -f - -o - | tee ~/Pictures/Screenshots/slurp/$(date '+%Y_%m_%d_%H%M%S').png | wl-copy
}

without_slurp() {
  grim - | swappy -f - -o - | tee ~/Pictures/Screenshots/fullscreen/$(date '+%Y_%m_%d_%H%M%S').png | wl-copy
}

if [[ "$1" == "slurp" ]]; then
  with_slurp
  notify-send -a 'Grim' -u low 'Screenshot' "Screenshot saved with Swappy"
elif [[ "$1" == "no_slurp" ]]; then
  without_slurp
  notify-send -a 'Grim' -u low 'Screenshot' "FullScreen screenshot saved with Swappy"
fi

