#!/bin/bash

case $1 in
    up)
        # Unmute
        amixer -D pulse set Master on >/dev/null
        # +5%
        amixer -D pulse set Master 5%+ >/dev/null
        ;;
    down)
        # Unmute
        amixer -D pulse set Master on >/dev/null
        # -5%
        amixer -D pulse set Master 5%- >/dev/null
        ;;
    mute)
        # Toggle mute
        amixer -D pulse set Master 1+ toggle >/dev/null
        ;;
esac
