#! /bin/sh
export SXHKD_SHELL=/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 #8 9 10

bspc config border_width         2
bspc config focused_border_color "#CCCCCC"
bspc config normal_border_color "#7D7D7D"
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


nitrogen --restore &
nm-applet &
xsetroot -cursor_name left_ptr &
flameshot &
dunst &
picom -b &
~/.config/polybar/scripts/launch.sh &
xss-lock --transfer-sleep-lock -- bash ~/.config/sxhkd/scripts/lock.sh
