#! /bin/sh
export SXHKD_SHELL=/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 #8 9 10

bspc config border_width         2
bspc config focused_border_color "#56949f"
bspc config normal_border_color "#908caa"
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a TelegramDesktop desktop='^2'


nitrogen --restore &
nm-applet &
xsetroot -cursor_name left_ptr &
setxkbmap -model pc105 -layout us,ru -option grp:win_space_toggle &
flameshot &
dunst &
picom -b &
udiskie &
$HOME/.config/polybar/launch.sh &
xautolock $HOME/.config/sxhkd/scripts/lock.sh
#~/dotfiles/scripts/fullscreen &
